packages:
  - 'api'
  - 'app'
  - 'admin'
  - 'packages/*'
allowBuilds:
  '@nestjs/core': true
  '@prisma/engines': true
  '@scarf/scarf': true
  msgpackr-extract: true
  prisma: true
  puppeteer: false
  sharp: true
  unrs-resolver: true
